import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedRegistrationMode {
  final List<RegistrationModeModel> results;

  AutogeneratedRegistrationMode({this.results});

  factory AutogeneratedRegistrationMode.fromJson(Map<String, dynamic> json) {
    List<RegistrationModeModel> temp;
    if (json['results'] != null) {
      temp = List<RegistrationModeModel>();
      json['results'].forEach((v) {
        temp.add(RegistrationModeModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedRegistrationMode(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class RegistrationModeModel extends Equatable {
  final int id;
  final String name;

  RegistrationModeModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory RegistrationModeModel.fromJson(Map<String, dynamic> json) {
    return RegistrationModeModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
