import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedProductDetail {
  final List<ProductDetailModel> results;

  AutogeneratedProductDetail({this.results});

  factory AutogeneratedProductDetail.fromJson(Map<String, dynamic> json) {
    List<ProductDetailModel> temp;
    if (json['results'] != null) {
      temp = List<ProductDetailModel>();
      json['results'].forEach((v) {
        temp.add(ProductDetailModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedProductDetail(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ProductDetailModel extends Equatable {
  final int id;
  final String name;

  ProductDetailModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory ProductDetailModel.fromJson(Map<String, dynamic> json) {
    return ProductDetailModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
