name: wmn_plus
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_bloc: ^2.0.0
  equatable: ^0.6.1
  flutter_screenutil: ^0.6.0
  shared_preferences: ^0.5.3+5
  flutter_pagewise: ^1.2.3
  intl_translation: ^0.17.7
  web_socket_channel: ^1.1.0
  easy_localization: ^1.3.1
  carousel_slider: ^1.3.0
  flutter_calendar_carousel: ^1.4.9
  infinite_listview: ^1.0.1+1
  flutter_html: ^0.11.1
  curved_navigation_bar: ^0.3.1
  webview_flutter: ^0.3.15+1
  flutter_launch: ^0.2.0
  url_launcher: ^5.0.3
  get_it: ^1.0.3+2
  firebase_messaging: ^6.0.1
  share: ^0.6.3
  table_calendar: ^2.2.1
  page_transition: ^1.1.5
  flutter_staggered_grid_view: ^0.2.2
  flare_flutter: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/app_icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/login_logo.png
    - assets/doctor_login_logo.png
    - path/en-US.json
    - path/ru-RU.json
    - path/ar-DZ.json
    - path/kk-KZ.json
    - assets/doctor_login_logo.png
    - assets/kazakhstan.png
    - assets/russia.png
    - assets/united-kingdom.png
    - assets/check.flr
    - assets/fert_photo.jpg
    - assets/preg_photo.jpg
    - assets/climax_photo.jpg
