import 'package:equatable/equatable.dart';

class AutogeneratedChangeModeFertility {
  final List<ChangeModeFertilityModel> results;

  AutogeneratedChangeModeFertility({this.results});

  factory AutogeneratedChangeModeFertility.fromJson(Map<String, dynamic> json) {
    List<ChangeModeFertilityModel> temp;
    if (json['results'] != null) {
      temp = List<ChangeModeFertilityModel>();
      json['results'].forEach((v) {
        temp.add(ChangeModeFertilityModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedChangeModeFertility(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ChangeModeFertilityModel extends Equatable {
  final int id;
  final String name;

  ChangeModeFertilityModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory ChangeModeFertilityModel.fromJson(Map<String, dynamic> json) {
    return ChangeModeFertilityModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
