import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedNews {
  final List<NewsModel> results;

  AutogeneratedNews({this.results});

  factory AutogeneratedNews.fromJson(Map<String, dynamic> json) {
    List<NewsModel> temp;
    if (json['result'] != null) {
      temp = List<NewsModel>();
      json['result'].forEach((v) {
        temp.add(NewsModel.fromJson(v));
      });
    }
    return AutogeneratedNews(results: temp);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class NewsModel extends Equatable {
  final int id;
  final String name;

  NewsModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory NewsModel.fromJson(Map<String, dynamic> json) {
    return NewsModel(json['id'], json['title']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
