import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedNews {
  final List<NewsModel> results;

  AutogeneratedNews({this.results});

  factory AutogeneratedNews.fromJson(Map<String, dynamic> json) {
    List<NewsModel> temp;
    if (json['result'] != null) {
      temp = List<NewsModel>();
      json['result'].forEach((v) {
        temp.add(NewsModel.fromJson(v));
      });
    }
    return AutogeneratedNews(results: temp);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class NewsModel extends Equatable {
  final int id;
  final String name;
  final String image;

  NewsModel(this.id, this.name, this.image);

  @override
  List<Object> get props => [id, name, image];

  factory NewsModel.fromJson(Map<String, dynamic> json) {
    return NewsModel(json['id'], json['title'],json['image_url']);
  }

  get imageUrl => "http://194.146.43.98:4000/image?uri=" + this.image;

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['image_url'] = this.image;
    return data;
  }
  
}
