import 'dart:async';
import 'dart:convert';

import 'package:http/http.dart';
import 'package:wmn_plus/features/news/news_model.dart';

class NewsProvider {
  Future<void> loadAsync(String token) async {
    /// write from keystore/keychain
    await Future.delayed(Duration(seconds: 2));
  }

  Future<List<NewsModel>> fetchMoreNews(int pageIndex, int category) async {
    /// write from keystore/keychain
    Response response;
    try {
      print(category.toString() + "  sSSSSS");
      response = await post('http://194.146.43.98:4000/api/v1/patient/news',
          body: json.encode({'id': category, 'pageIndex': pageIndex}),
          headers: {
            "Content-Type": "application/json",
            "Authorization": "wmn538179 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Iis3KDcwNSk3MDA3MDcwIn0.ws6gC_mskJSaLr_tGNifdvl2ogAMX27b0Z0MQRDfpsg",
          });
      String body = utf8.decode(response.bodyBytes);
      Map newsObject = json.decode(body);
      var newsList = AutogeneratedNews.fromJson(newsObject);
      print(body);
      return newsList.results;
    } catch (error) {
      print(error);
      throw (error.toString());
    }
  }

  Future<void> saveAsync(String token) async {
    /// write from keystore/keychain
    await Future.delayed(Duration(seconds: 2));
  }

  void test(bool isError) {
    if (isError == true) {
      throw Exception("manual error");
    }
  }
}
