import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedChangeModePregnancy {
  final List<ChangeModePregnancyModel> results;

  AutogeneratedChangeModePregnancy({this.results});

  factory AutogeneratedChangeModePregnancy.fromJson(Map<String, dynamic> json) {
    List<ChangeModePregnancyModel> temp;
    if (json['results'] != null) {
      temp = List<ChangeModePregnancyModel>();
      json['results'].forEach((v) {
        temp.add(ChangeModePregnancyModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedChangeModePregnancy(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ChangeModePregnancyModel extends Equatable {
  final int id;
  final String name;

  ChangeModePregnancyModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory ChangeModePregnancyModel.fromJson(Map<String, dynamic> json) {
    return ChangeModePregnancyModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
