import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedFertilityDuration {
  final List<FertilityDurationModel> results;

  AutogeneratedFertilityDuration({this.results});

  factory AutogeneratedFertilityDuration.fromJson(Map<String, dynamic> json) {
    List<FertilityDurationModel> temp;
    if (json['results'] != null) {
      temp = List<FertilityDurationModel>();
      json['results'].forEach((v) {
        temp.add(FertilityDurationModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedFertilityDuration(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class FertilityDurationModel extends Equatable {
  final int id;
  final String name;

  FertilityDurationModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory FertilityDurationModel.fromJson(Map<String, dynamic> json) {
    return FertilityDurationModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
