import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedLanguage {
  final List<LanguageModel> results;

  AutogeneratedLanguage({this.results});

  factory AutogeneratedLanguage.fromJson(Map<String, dynamic> json) {
    List<LanguageModel> temp;
    if (json['results'] != null) {
      temp = List<LanguageModel>();
      json['results'].forEach((v) {
        temp.add(LanguageModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedLanguage(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class LanguageModel extends Equatable {
  final int id;
  final String name;

  LanguageModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory LanguageModel.fromJson(Map<String, dynamic> json) {
    return LanguageModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
