import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedDiscountDetail {
  final List<DiscountDetailModel> results;

  AutogeneratedDiscountDetail({this.results});

  factory AutogeneratedDiscountDetail.fromJson(Map<String, dynamic> json) {
    List<DiscountDetailModel> temp;
    if (json['results'] != null) {
      temp = List<DiscountDetailModel>();
      json['results'].forEach((v) {
        temp.add(DiscountDetailModel.fromJson(v));
      });
    }
    return AutogeneratedDiscountDetail(results: temp);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class DiscountDetailModel extends Equatable {
  final int id;
  final String name;

  DiscountDetailModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory DiscountDetailModel.fromJson(Map<String, dynamic> json) {
    return DiscountDetailModel(json['id'], json['name']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
