import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedChangeModeFertilityDuration {
  final List<ChangeModeFertilityDurationModel> results;

  AutogeneratedChangeModeFertilityDuration({this.results});

  factory AutogeneratedChangeModeFertilityDuration.fromJson(Map<String, dynamic> json) {
    List<ChangeModeFertilityDurationModel> temp;
    if (json['results'] != null) {
      temp = List<ChangeModeFertilityDurationModel>();
      json['results'].forEach((v) {
        temp.add(ChangeModeFertilityDurationModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedChangeModeFertilityDuration(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ChangeModeFertilityDurationModel extends Equatable {
  final int id;
  final String name;

  ChangeModeFertilityDurationModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory ChangeModeFertilityDurationModel.fromJson(Map<String, dynamic> json) {
    return ChangeModeFertilityDurationModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
