import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedNewsDetail {
  final List<NewsDetailModel> results;

  AutogeneratedNewsDetail({this.results});

  factory AutogeneratedNewsDetail.fromJson(Map<String, dynamic> json) {
    List<NewsDetailModel> temp;
    if (json['results'] != null) {
      temp = List<NewsDetailModel>();
      json['results'].forEach((v) {
        temp.add(NewsDetailModel.fromJson(v));
      });
    }
    return AutogeneratedNewsDetail(results: temp);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class NewsDetailModel extends Equatable {
  final int id;
  final String name;

  NewsDetailModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory NewsDetailModel.fromJson(Map<String, dynamic> json) {
    return NewsDetailModel(json['id'], json['name']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
