import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedPregnantMode {
  final List<PregnantModeModel> results;

  AutogeneratedPregnantMode({this.results});

  factory AutogeneratedPregnantMode.fromJson(Map<String, dynamic> json) {
    List<PregnantModeModel> temp;
    if (json['results'] != null) {
      temp = List<PregnantModeModel>();
      json['results'].forEach((v) {
        temp.add(PregnantModeModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedPregnantMode(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PregnantModeModel extends Equatable {
  final int id;
  final String name;

  PregnantModeModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory PregnantModeModel.fromJson(Map<String, dynamic> json) {
    return PregnantModeModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
