import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedCategoryDetail {
  final List<CategoryDetailModel> results;

  AutogeneratedCategoryDetail({this.results});

  factory AutogeneratedCategoryDetail.fromJson(Map<String, dynamic> json) {
    List<CategoryDetailModel> temp;
    if (json['results'] != null) {
      temp = List<CategoryDetailModel>();
      json['results'].forEach((v) {
        temp.add(CategoryDetailModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedCategoryDetail(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class CategoryDetailModel extends Equatable {
  final int id;
  final String name;

  CategoryDetailModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory CategoryDetailModel.fromJson(Map<String, dynamic> json) {
    return CategoryDetailModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
