import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedFertilityPeriod {
  final List<FertilityPeriodModel> results;

  AutogeneratedFertilityPeriod({this.results});

  factory AutogeneratedFertilityPeriod.fromJson(Map<String, dynamic> json) {
    List<FertilityPeriodModel> temp;
    if (json['results'] != null) {
      temp = List<FertilityPeriodModel>();
      json['results'].forEach((v) {
        temp.add(FertilityPeriodModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedFertilityPeriod(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class FertilityPeriodModel extends Equatable {
  final int id;
  final String name;

  FertilityPeriodModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory FertilityPeriodModel.fromJson(Map<String, dynamic> json) {
    return FertilityPeriodModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
