import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedProfile {
  final List<ProfileModel> results;

  AutogeneratedProfile({this.results});

  factory AutogeneratedProfile.fromJson(Map<String, dynamic> json) {
    List<ProfileModel> temp;
    if (json['results'] != null) {
      temp = List<ProfileModel>();
      json['results'].forEach((v) {
        temp.add(ProfileModel.fromJson(v));
      });
    }
    return AutogeneratedProfile(results: temp);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ProfileModel extends Equatable {
  final int id;
  final String name;

  ProfileModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory ProfileModel.fromJson(Map<String, dynamic> json) {
    return ProfileModel(json['id'], json['name']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
