import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedDiscounts {
  final List<DiscountsModel> results;

  AutogeneratedDiscounts({this.results});

  factory AutogeneratedDiscounts.fromJson(Map<String, dynamic> json) {
    List<DiscountsModel> temp;
    if (json['results'] != null) {
      temp = List<DiscountsModel>();
      json['results'].forEach((v) {
        temp.add(DiscountsModel.fromJson(v));
      });
    }
    return AutogeneratedDiscounts(results: temp);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class DiscountsModel extends Equatable {
  final int id;
  final String name;

  DiscountsModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory DiscountsModel.fromJson(Map<String, dynamic> json) {
    return DiscountsModel(json['id'], json['name']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
